name: Homepage CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    uses: ethn1ee/pi/.github/workflows/docker-publish.yaml@main
    with:
      image_name: pi-homepage
    secrets: inherit

  update-pointer:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Call Submodule Update Workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ethn1ee',
              repo: 'pi',
              workflow_id: 'sync-submodule.yaml',
              ref: 'main',
              inputs: {
                app_path: 'apps/homepage'
              }
            });
