name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Call Release Workflow
    permissions:
      contents: write
      packages: write
    uses: ethn1ee/pi/.github/workflows/release.yaml@main
    with:
      chart_path: charts/homepage
      image_name: pi-api-homepage
      image_tag: ${{ github.sha }}
    secrets: inherit
