name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish
    permissions:
      contents: read
      packages: write
    uses: ethn1ee/pi/.github/workflows/docker-publish.yaml@main
    with:
      image_name: pi-homepage
    secrets: inherit
